apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-seym
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0036-tenant/tkrw-pr712-0075-0036-app/devfile-sample-seym@sha256:fb4a70a649dd17c420886d8816ee3588cbf659f150fb5f8f0cd0cf53491c136b
        name: my-nodejs
        resources: {}
status: {}
